### ISSUE TITLE
best-practices

### ISSUE THREAD

**Issue by SigidinIlya** [MaximShmatov/toxin#11]
[Данный пункт 2.11](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) гласит, что все тэги должны содержать в себе класс. 

![image](https://user-images.githubusercontent.com/70949093/101098567-31d03680-35d4-11eb-8bb9-2e02ac26cfe0.png)

А зачем здесь приставка 'div' ? 

![image](https://user-images.githubusercontent.com/70949093/101098609-41e81600-35d4-11eb-88cc-137bac7b230a.png)

**Comment by Hahahayabanan** [comment]
Можно закрыть
