### ISSUE TITLE
Интерфейсы миксинов

### ISSUE THREAD

**Issue by SigidinIlya** [MaximShmatov/toxin#12]
![image](https://user-images.githubusercontent.com/70949093/101800655-8f0d4000-3b1e-11eb-98aa-b8295eedb2aa.png)

В данном примере как разработчик поймёт все возможные значения темы? (посмотреть в SCSS не считается)) т.к во время разработки необходимо свой код проектировать так, чтобы облегчать друг другу работу).
Так же здесь нарушается правило миксования, и я могу по сути использовать любое слово, которое по итогу станет классом элемента. В общем, такие места нужно сделать по аналогии с компонентом button (как мы обсуждали)

**Comment by Hahahayabanan** [comment]
Используй разыменование во всех блоках, чтобы не искать каждый раз какие параметры может принять миксин.

![image](https://user-images.githubusercontent.com/43137324/106708172-780d3a80-6603-11eb-881a-fb55cc04d708.png)

Можно сделать это прямо в параметрах примерно так

`bullet-list({ title='bullet-list', items=[{ name='item1', value='value1 '},  { name='item2', value='value2 '} ]  } = {})`

И не забывай добавлять пустой объект, как значение по-умолчанию для миксина

**Comment by Hahahayabanan** [comment]
Надо привести код к единообразию. Как по мне, лучше использовать разыменование в параметрах

![image](https://user-images.githubusercontent.com/43137324/107190677-264a2300-69fc-11eb-830b-99ddf2c973a0.png)
![image](https://user-images.githubusercontent.com/43137324/107190703-2f3af480-69fc-11eb-9a74-6ab6aed2b5e8.png)

**Comment by Hahahayabanan** [comment]
Не везде исправлено

![image](https://user-images.githubusercontent.com/43137324/107746906-aa1b4c80-6d27-11eb-9721-7a2f31ef079e.png)
![image](https://user-images.githubusercontent.com/43137324/107746928-b1425a80-6d27-11eb-8a69-416e13f01539.png)

Надо добавить скобочки всем миксинам для соблюдения однообразия, чтобы каждый раз даже, если у нас нет входных параметров, не думать нужно при вызове добавить скобочки или не нужно

![image](https://user-images.githubusercontent.com/43137324/107746957-bb645900-6d27-11eb-8d73-ffdea5779e22.png)

**Comment by Hahahayabanan** [comment]
Тут, возможно, стоит использовать именованные свойства объекта, вместо массива, иначе непонятно какой элемент чем должен являться

![image](https://user-images.githubusercontent.com/43137324/108171369-7c118000-710c-11eb-8c14-8812765bc065.png)

**Comment by Hahahayabanan** [comment]
Можно закрыть
