### ISSUE TITLE
Хардкод

### ISSUE THREAD

**Issue by SigidinIlya** [MaximShmatov/toxin#5]
![image](https://user-images.githubusercontent.com/70949093/99455478-f3324f00-2938-11eb-9f48-2c5887f673b0.png)

Сейчас по всем компонентам используется хардкод, компоненты должны иметь возможность переиспользования, поэтому все динамические данные должны приходить в них из внешнего мира

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/100397050-d98bb880-3058-11eb-960d-012b7643a0ac.png)

Хардкод всё ещё присутствует :C (pull я делал)

**Comment by SigidinIlya** [comment]
В остальных компонентах так же хардкод нужно убрать.
![image](https://user-images.githubusercontent.com/70949093/101096835-3515f300-35d1-11eb-9eb5-8da89140390f.png)

**Comment by SigidinIlya** [comment]
В коде по прежнему в большинстве компонентов остался хардкод 
![image](https://user-images.githubusercontent.com/70949093/101798675-6ab06400-3b1c-11eb-8ed3-ede86e2a2c1d.png)
Поправь глобально плз

**Comment by Hahahayabanan** [comment]
Почему не передавать эти значения, как параметр миксина, там, где он был вызван?)

![image](https://user-images.githubusercontent.com/43137324/106706312-8a39a980-6600-11eb-9a97-8fc5a4b9e57c.png)

А этот код вносит неочевидность в поведение. Для сохранения инкапсуляции не стоит использовать селектор блока за его пределами

![image](https://user-images.githubusercontent.com/43137324/106706585-f1575e00-6600-11eb-9b67-2c4715871253.png)

**Comment by Hahahayabanan** [comment]
В других местах тоже нужно поправить)

![image](https://user-images.githubusercontent.com/43137324/107189812-036b3f00-69fb-11eb-98b8-bf15e8dec1ba.png)

**Comment by Hahahayabanan** [comment]
Тут всё-ещё хардкод.

**Comment by Hahahayabanan** [comment]
Всё-ещё хардкод. Избавиться от него нужно для того, чтобы была возможность переиспользования блоков на разных страницах / в разных местах одной страницы с различным набором входных данных. 

Например, здесь миксин должен принимать массив объектов с полями name, caption, isChecked
Если нам понадобится список с другими чекбоксами, то можно использовать этот блок передать нужные значения в миксин

![image](https://user-images.githubusercontent.com/43137324/107744206-5ad31d00-6d23-11eb-98b5-6a3140e1acca.png)

**Comment by Hahahayabanan** [comment]
И здесь, эти значения лучше передавать, как параметр

![image](https://user-images.githubusercontent.com/43137324/107744901-8e627700-6d24-11eb-9b13-54ce548ce9cd.png)

**Comment by Hahahayabanan** [comment]
Эти тоже) Для упрощения и сокращения кода, можешь написать функцию прямо в pug, чтобы частично автоматизировать запись

![image](https://user-images.githubusercontent.com/43137324/107745176-edc08700-6d24-11eb-9179-456cdb788f31.png)

**Comment by Hahahayabanan** [comment]
Список ссылок тоже можно вынести в параметры, как массив 

![image](https://user-images.githubusercontent.com/43137324/108172487-f8589300-710d-11eb-92fb-f02442652b89.png)

**Comment by Hahahayabanan** [comment]
Не, лучше сделать массивом с произвольным набором ссылок, чтобы можно было в любой момент изменить их количество/порядок/состав и т.д. Примерно, как сейчас сделано в футере

![image](https://user-images.githubusercontent.com/43137324/108469159-d3dcf200-7298-11eb-9a96-38004f51b58f.png)

**Comment by Hahahayabanan** [comment]
Есть привязка к значениям, это тоже нужно вынести из блока и сделать универсальным для любых входных данных

![image](https://user-images.githubusercontent.com/43137324/110074065-9b0d4480-7d91-11eb-9f32-2e45f23df829.png)

**Comment by Hahahayabanan** [comment]
Массив значений нужно вынести в параметры миксина и обходить их массивом, может понадобиться сделать dropdown с любым другим набором данных и тогда придётся раз за разом переписывать этот компонент или пилить ещё один такой же

![image](https://user-images.githubusercontent.com/43137324/111324465-da823d80-867b-11eb-888d-8933000b1de0.png)

Проблема не решена, блок всё-ещё может работать только с гостями и комнатами

![image](https://user-images.githubusercontent.com/43137324/111324405-cfc7a880-867b-11eb-9546-dae576d51bf0.png)

**Comment by Hahahayabanan** [comment]
Можно закрыть
