### ISSUE TITLE
Примеси

### ISSUE THREAD

**Issue by SigidinIlya** [MaximShmatov/toxin#6]
![image](https://user-images.githubusercontent.com/70949093/99456408-6a1c1780-293a-11eb-85fe-614427d73a9f.png)
![image](https://user-images.githubusercontent.com/70949093/99456458-80c26e80-293a-11eb-945e-4bd6427148e8.png)

По нашим стандартам, нельзя использовать примеси на элементах.
Получается, header стилизует кнопку, но каждый компонент должен отвечать только за себя.

![image](https://user-images.githubusercontent.com/70949093/99456546-a3ed1e00-293a-11eb-93ba-0f0fea92a274.png)

Более подробно об этом можно почитать [Здесь](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.5)

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/100397118-2d969d00-3059-11eb-8e2e-7b41fe6ef97b.png)

В копирайте вижу осталась возможность прокидывания любого класса из пропсов.

**Comment by Hahahayabanan** [comment]
Можно закрыть
