### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by SigidinIlya** [MaximShmatov/toxin#7]
![image](https://user-images.githubusercontent.com/70949093/99457069-6fc62d00-293b-11eb-89cf-fd9450743577.png)

В этом блоке довольно неясная логика. Лейбл - блок, с классом checkbox это окей, но почему далее инпут с классом checkbox__true, и ДИВ с классом checkbox__false, класснеймы лучше переименовать во что-то более очевидное ? И является ли использование такого разделение сущностей (див и инпут) необходимым ?)

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/100396858-e360ec00-3057-11eb-8bed-222d8166beea.png)

По БЭМу в помимо указанного модификатора не хватает основного класса.
Во вторых, на текущий момент сильно нарушена инкапсуляция данного компонента. В пропсах компонент должен ожидать возможные значения темы, будь то size: 'large' | 'small', color: 'red' | 'green' и т.д.
Все полученные значения из темы уже в компоненте должны вычисляться и конкатенироваться в один общий класс.

**Comment by SigidinIlya** [comment]
Исходя из БЭМ документации  [ТЫК](https://ru.bem.info/methodology/quick-start/#%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82)

Может ли элемент находиться без блока? 

__title - элемент
__items - элемент

![image](https://user-images.githubusercontent.com/70949093/101799012-b400b380-3b1c-11eb-86f7-e3b8afaf7401.png)

**Comment by SigidinIlya** [comment]
Здесь не совсем корректное БЭМ именование.

![image](https://user-images.githubusercontent.com/70949093/101800215-173f1580-3b1e-11eb-98fd-6a57c65d4457.png)

**Comment by Hahahayabanan** [comment]
В классе блока не должно быть информации о том, как и где этот блок будет использован, это противоречит идее независимости и переиспользованию

![image](https://user-images.githubusercontent.com/43137324/106706972-85c1c080-6601-11eb-8485-1c694db402c5.png)

**Comment by Hahahayabanan** [comment]
Элемент - имя существительное, [по стандартам](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

![image](https://user-images.githubusercontent.com/43137324/106707442-45af0d80-6602-11eb-9c14-a0a0ea952cc8.png)

**Comment by Hahahayabanan** [comment]
Имя элемента должно быть чуть более содержательное)

![image](https://user-images.githubusercontent.com/43137324/107190090-6a88f380-69fb-11eb-9d4a-1c38f93c471f.png)

**Comment by Hahahayabanan** [comment]
Нужно попытаться назвать модификатор так, чтобы было понятно какие свойства он изменит у элемента и чем он отличается от других

![image](https://user-images.githubusercontent.com/43137324/107190189-91dfc080-69fb-11eb-91f1-e11c24ce0792.png)

**Comment by Hahahayabanan** [comment]
Такие имена совсем не читаемые) Имя модификатора не должно быть привязано к конкретным значениям свойств, `должен удовлетворять свойствам модификатора из английского языка. Всегда adjective или adjectival phrase`

Нужно спроектировать компоненту так, чтобы удовлетворять данным условиям

И, кстати, тут нужен рефакторинг, т.к. высота и ширина не должна быть задана фиксированными значениями [П.1.12](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#1.12) [П.2.5](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.5)

![image](https://user-images.githubusercontent.com/43137324/107746204-7ab81000-6d26-11eb-81c0-da7716711313.png)

**Comment by Hahahayabanan** [comment]
True, false - это значения свойств. Имя элемента должно быть существительным, отражающим его сущность, а не состояние, для этого есть модификаторы [П.4.1](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1)

![image](https://user-images.githubusercontent.com/43137324/107746558-121d6300-6d27-11eb-9a93-cbceaebc4c32.png)

**Comment by Hahahayabanan** [comment]
visible hidden - что?)

![image](https://user-images.githubusercontent.com/43137324/108172826-5d13ed80-710e-11eb-8eeb-4d0aceb0f000.png)

**Comment by Hahahayabanan** [comment]
Можно закрыть
